# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20240528-151625-central-dam

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: pt

pipeline:
- name: SpacyNLP
  model: "pt_core_news_md"
- name: SpacyTokenizer
- name: SpacyEntityExtractor
  dimensions: ["GPE"]
- name: CRFEntityExtractor
  features:
    - ["low", "title", "upper"]
    - ["bias", "low", "prefix5", "prefix2", "suffix5", "suffix3", "suffix2", "suffix1", "digit"]
    - ["low", "title", "upper"]
- name: EntitySynonymMapper
- name: RegexEntityExtractor
  case_sensitive: false
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 300
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 300
  - name: TEDPolicy
    max_history: 5
    epochs: 300
    constrain_similarities: true
